"""empty message

Revision ID: 88b24eda9a3f
Revises: 
Create Date: 2024-10-09 17:16:59.342081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88b24eda9a3f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('user_password', sa.String(length=255), nullable=True),
    sa.Column('user_sweet_word', sa.String(length=255), nullable=True),
    sa.Column('user_status', sa.Boolean(), nullable=True, comment='0-Pending, 1-Approved'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('task_user_id', sa.Integer(), nullable=True),
    sa.Column('task_title', sa.Text(), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=True),
    sa.Column('task_due_date', sa.Date(), nullable=True),
    sa.Column('task_status', sa.String(length=255), nullable=True, comment='0-Pending, 2-In Progress, 1-Completed'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('user_session',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('session_email', sa.String(length=255), nullable=True),
    sa.Column('session_token', sa.String(length=955), nullable=True),
    sa.Column('session_user', sa.Integer(), nullable=True),
    sa.Column('session_expiry', sa.DateTime(), nullable=True),
    sa.Column('session_status', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_user'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_user_session_session_id'), 'user_session', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_session_session_id'), table_name='user_session')
    op.drop_table('user_session')
    op.drop_table('tasks')
    op.drop_table('users')
    # ### end Alembic commands ###
